# (1) import libraries

In [1]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

import numpy as np
import time

# (2) preparing iris dataset

In [3]:
iris = datasets.load_iris()

# get training and testing indexes randomly
train_indx = np.random.choice(range(0, 150), int(iris.target.shape[0]/100*60), replace=False)
test_indx = np.array([indx for indx in np.arange(0, 150, 1) if indx not in train_indx])

x_train = iris.data[train_indx, :]
y_train = iris.target[train_indx]

x_test = iris.data[test_indx, :]
y_test = iris.target[test_indx]

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(90, 4)
(90,)
(60, 4)
(60,)


# (3) parameters estimation

In [4]:
mu_0 = np.mean(x_train[y_train == 0], axis=0)
sigma_0 = np.cov(x_train[y_train == 0], rowvar=0)
print(mu_0)
print(sigma_0)

mu_1 = np.mean(x_train[y_train == 1], axis=0)
sigma_1 = np.cov(x_train[y_train == 1], rowvar=0)
print(mu_1)
print(sigma_1)

mu_2 = np.mean(x_train[y_train == 2], axis=0)
sigma_2 = np.cov(x_train[y_train == 2], rowvar=0)
print(mu_2)
print(sigma_2)

[5.07142857 3.5        1.49285714 0.25714286]
[[0.10878307 0.07851852 0.00978836 0.0131746 ]
 [0.07851852 0.1162963  0.00407407 0.0162963 ]
 [0.00978836 0.00407407 0.02365079 0.00375661]
 [0.0131746  0.0162963  0.00375661 0.01365079]]
[5.90588235 2.73529412 4.27058824 1.32352941]
[[0.29087344 0.08857398 0.19139037 0.06137255]
 [0.08857398 0.08538324 0.07197861 0.0312656 ]
 [0.19139037 0.07197861 0.20516934 0.06283422]
 [0.06137255 0.0312656  0.06283422 0.03276292]]
[6.60357143 2.92142857 5.55357143 2.01071429]
[[0.32480159 0.03547619 0.25535714 0.04699735]
 [0.03547619 0.05656085 0.01843915 0.02791005]
 [0.25535714 0.01843915 0.26850529 0.04458995]
 [0.04699735 0.02791005 0.04458995 0.06839947]]


# (4) bayesian decision making

In [5]:
gnb = GaussianNB()

y_pred = gnb.fit(x_train, y_train).predict(x_test)
print('Testing classification accuracy: %.4f' % ((y_test == y_pred).sum()/x_test.shape[0]))

Testing classification accuracy: 0.9500
